### ISSUE TITLE
Is it possible to render the applications that depend on an application in the documentation view?

### ISSUE THREAD

**Issue by lhaig** [AOEpeople/vistecture#7]
Version 0.5.3
OS: LinuxMint
 
Thanks for a great project and I see quite a bit of potential for me to use in my day to day job.

I have been asked if we can list the applications that are dependent on the viewed application in the text below the svg image. In the html provided by the documentation export.

I can't see an easy way but I am no Go developer so I might have missed it.
Also the application map is not sorted alphabetically is it possible to do in the template?

Thanks for the project

**Comment by danielpoe** [comment]
@lhaig 

Sorry for late reply.

In the htmldocumentation template provided you can use the generated svg image that shows incoming dependencies.


But since in gotemplates it is not possible to call methods with more than one parameter you cannot get the list of incoming dependencies..

We will add this in the next version

Cheers

**Comment by danielpoe** [comment]
This is now possible with the method "FindAllApplicationsThatReferenceApplication" in the Project struct

**Comment by lhaig** [comment]
I know it is a closed issue but could you perhaps show me an example of how I would call this in the template?
I have been trying for a few days now and my googling has not been successful.
Thanks for the help
